/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Malcolm
 */
public class CRUDCommuneFrance extends javax.swing.JFrame {

    private List<String> ilistCommunes = new ArrayList();
    private int iiPosition = 1;
    private int iiCount;
  
    

    /**
     * Creates new form CRUDCommuneFrance
     * @throws java.io.IOException
     */
    public CRUDCommuneFrance() throws IOException {
        initComponents();
        this.remplirListes();
        iiCount = ilistCommunes.size() - 1;
        
        //this.setLocation(new Point(300, 200));
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(153, 0, 102));
//        this.jButtonPremier.setEnabled(false);
//        this.jButtonPrecedent.setEnabled(false);
//        this.jButtonSuivant.setEnabled(false);
//        this.jButtonDernier.setEnabled(false);

        //this.setLocation(new Point(300, 200));
        this.setLocationRelativeTo(null);

        try {
            // --- Bufferisation
            try ( // --- Ouverture du fichier
                    FileReader lfrFichier = new FileReader("communes_insee.csv")) {
                // --- Bufferisation
                BufferedReader lbrBuffer = new BufferedReader(lfrFichier);
                
                // --- Lecture des lignes-enregistrements
                // --- Remplissage du tableau
                String lsLigne;
                while ((lsLigne = lbrBuffer.readLine()) != null) {
                    this.ilistCommunes.add(lsLigne);
                }
                lbrBuffer.close();
            }

            // --- Divers
            iiCount = ilistCommunes.size() - 1;

            this.setVisible(true);
        } catch (FileNotFoundException e) {
            this.jLabelCompteur.setText(e.getMessage());
            System.err.println(e);

        } catch (IOException e) {
            this.jLabelCompteur.setText(e.getMessage());
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelINSEE = new javax.swing.JLabel();
        jTextFieldINSEE = new javax.swing.JTextField();
        jLabelDepartement = new javax.swing.JLabel();
        jComboBoxDepartements = new javax.swing.JComboBox();
        jButtonPremier = new javax.swing.JButton();
        jButtonPrecedent = new javax.swing.JButton();
        jButtonSuivant = new javax.swing.JButton();
        jButtonDernier = new javax.swing.JButton();
        jButtonCLS = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSuprimer = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabelCompteur = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.magenta);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabelNom.setText("Nom :");

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabelCP.setText("Code postal :");

        jLabelINSEE.setText("INSEE :");

        jLabelDepartement.setText("Département :");

        jComboBoxDepartements.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Départements" }));
        jComboBoxDepartements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartementsActionPerformed(evt);
            }
        });

        jButtonPremier.setText("<<");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButtonPremier, org.jdesktop.beansbinding.ELProperty.create("${icon.iconHeight}"), jButtonPremier, org.jdesktop.beansbinding.BeanProperty.create("border"));
        bindingGroup.addBinding(binding);

        jButtonPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPremierActionPerformed(evt);
            }
        });

        jButtonPrecedent.setText("<");
        jButtonPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrecedentActionPerformed(evt);
            }
        });

        jButtonSuivant.setText(">");
        jButtonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuivantActionPerformed(evt);
            }
        });

        jButtonDernier.setText(">>");
        jButtonDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDernierActionPerformed(evt);
            }
        });

        jButtonCLS.setText("Clear");
        jButtonCLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonSuprimer.setText("Suprimer");
        jButtonSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuprimerActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNom)
                                    .addComponent(jLabelCP)
                                    .addComponent(jLabelDepartement)
                                    .addComponent(jLabelINSEE)
                                    .addComponent(jButtonCLS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldINSEE)
                                .addComponent(jTextFieldNom)
                                .addComponent(jTextFieldCP)
                                .addComponent(jComboBoxDepartements, 0, 238, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPrecedent)
                                    .addComponent(jButtonAjouter))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSuivant)
                                    .addComponent(jButtonSuprimer))
                                .addGap(23, 23, 23)
                                .addComponent(jButtonDernier, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonModifier)
                    .addComponent(jLabelCompteur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCP)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartement)
                    .addComponent(jComboBoxDepartements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelINSEE)
                    .addComponent(jTextFieldINSEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPremier)
                    .addComponent(jButtonPrecedent)
                    .addComponent(jButtonSuivant)
                    .addComponent(jButtonDernier))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSuprimer)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonCLS))
                .addGap(14, 14, 14)
                .addComponent(jLabelCompteur)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jComboBoxDepartementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartementsActionPerformed
        // TODO add your handling code here: 

        // jComboBoxDepartements.setText(tChamps[2]);
    }//GEN-LAST:event_jComboBoxDepartementsActionPerformed

    private void remplirListes() {
        ArrayList<String> arrayList = new ArrayList<>();
        for (String elem : arrayList) {
            System.out.println(elem);
        }

    }
    private void jButtonPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPremierActionPerformed
        // TODO add your handling code here:
        iiPosition = 1; // iiposition = iiposition +1
        affiche();
    }//GEN-LAST:event_jButtonPremierActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jButtonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuivantActionPerformed
        // TODO add your handling code here:
        // pour recuperer une ligne
        iiPosition++; // iiposition = iiposition +1
        affiche();
    }//GEN-LAST:event_jButtonSuivantActionPerformed

    private void jButtonPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrecedentActionPerformed
        // TODO add your handling code here:
        iiPosition--; // -- pour aller au precedente lignes 
        affiche();
    }//GEN-LAST:event_jButtonPrecedentActionPerformed

    private void jButtonDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDernierActionPerformed
        // TODO add your handling code here:
        iiPosition = ilistCommunes.size() - 1; // pour aller a la derniere ligne de la liste
        affiche();
    }//GEN-LAST:event_jButtonDernierActionPerformed

    private void jButtonCLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSActionPerformed
        // TODO add your handling code here:
        // pour clear les champs
        jTextFieldNom.setText("");
        jTextFieldCP.setText("");
        jTextFieldINSEE.setText("");
  
    }//GEN-LAST:event_jButtonCLSActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        // pour ajouter et ecrire dans le fichier csv  getText pour recuperer les champs
       String saisie = jTextFieldNom.getText(); 
              saisie += ";";
              
              saisie += jTextFieldCP.getText(); 
              saisie += ";";
              
              saisie += jComboBoxDepartements.getSelectedItem(); 
              saisie += ";";
              
              saisie += jTextFieldINSEE.getText();
              
             ilistCommunes.add(saisie);
             iiPosition = ++iiCount;// ma position actutuel es la fin du fichier. la fin augmente d'un.
             affiche();
       
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuprimerActionPerformed
// TODO add your handling code here:
        
        // pour suprimer une ligne dans mon fichier. 
    }//GEN-LAST:event_jButtonSuprimerActionPerformed
// a cause du void c une procedure/ fonction pcq ca n envoi rien
/*J'aurais pu faire ceci pour chaque boutton  mais plus bas jai fait une focntion affchife();
     appeller a chaque procedure.
    
     String lsLigne = this.ilistCommunes.get(iiPosition);
     String[] tChamps = lsLigne.split(";");
     jTextFieldNom.setText(tChamps[0]);
     */

    private void affiche() {
        String lsLigne = this.ilistCommunes.get(iiPosition);
        String[] tChamps = lsLigne.split(";");
        jTextFieldNom.setText(tChamps[0]);
        jTextFieldCP.setText(tChamps[1]);
        jTextFieldINSEE.setText(tChamps[3]);

        /// Boucle pour griser les boutton quand on a la 1ere ligne et a la dernier ligne
        //si les 2 premier boutton sont = 1 sont desactiver
        if ( iiPosition == 1){
            jButtonPremier.setEnabled(false);
            jButtonPrecedent.setEnabled(false);
           // sinon ils sont activer parce que on peut encore aller a l'arriere.
        }else{
            jButtonPremier.setEnabled(true);
            jButtonPrecedent.setEnabled(true);
        }// si on est a la derniere ligne de lecture de mon doc les deux suivant doit entre desativer
        //parce qu'on ne peut plus aller plus loins
        if ( iiPosition == ilistCommunes.size() - 1 ){
            jButtonSuivant.setEnabled(false);
            jButtonDernier.setEnabled(false);
           
        }else{// sinon  s'il y a possibileté d'aller plus loin ils sont activer
            jButtonSuivant.setEnabled(true);
            jButtonDernier.setEnabled(true);
        }
        
        // --- Affichage du compteur
        this.jLabelCompteur.setText((iiPosition + 1) + "/" + iiCount);
       
        // autre moyen si on garde toujour les boutton gris au debut
//        if (iiPosition == 1) {
//             jButtonPremier.setEnabled(false);
//            jButtonPrecedent.setEnabled(false);        
//        }
//        if (iiPosition == ilistCommunes.size() - 1) {
//           
//             jButtonSuivant.setEnabled(false);
//            jButtonDernier.setEnabled(false);  
//        }

    }
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDCommuneFrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDCommuneFrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDCommuneFrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDCommuneFrance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CRUDCommuneFrance().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CRUDCommuneFrance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonCLS;
    private javax.swing.JButton jButtonDernier;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonPrecedent;
    private javax.swing.JButton jButtonPremier;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JButton jButtonSuprimer;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBoxDepartements;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelCompteur;
    private javax.swing.JLabel jLabelDepartement;
    private javax.swing.JLabel jLabelINSEE;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldINSEE;
    private javax.swing.JTextField jTextFieldNom;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
